### ISSUE TITLE
bug: style list is get block by button

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#59] opened 2023-05-13 07:47 UTC
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/56c5b54f-5fb0-471d-b066-13962d28d1e6)

**Comment by Nevysha** [comment] 2023-05-13 08:28
Duplicate of #52

**Comment by Nevysha** [comment] 2023-05-14 16:47
fixed in release 2.0.2

**Closed by Nevysha** 2023-05-14 16:47 UTC
